#!/usr/bin/env bash
swaymsg -t get_tree &> /dev/null
if [[ $? == 0 ]]; then
    selected_workspace=$(swaymsg -t get_workspaces -r | jq -M '.[] | select(.focused==false and .visible==false) | .name' | tr -d '"' | bemenu -p 'change' --tf '#a3be8c' --tb '#2e3440' --nb '#2e3440' --fb '#2e3440' --hb '#2e3440' --hf '#d08770')
    current_output=$(swaymsg -t get_outputs --raw | jq '. | map(select(.focused == true)) | .[0].name' -r)
    if [[ $? != 0 ]]; then
	exit 1
    fi

    swaymsg "[workspace=${selected_workspace}]" move workspace to output "${current_output}"
    swaymsg workspace $selected_workspace
else
    selected_workspace=$(hyprctl workspaces | sed '/\(^\t.*\|^$\)/d' | awk -F '[()]' '{print $(NF-1)}' | bemenu -p 'change' --tf '#a3be8c' --tb '#2e3440' --nb '#2e3440' --fb '#2e3440' --hb '#2e3440' --hf '#d08770')
    hyprctl dispatch workspace name:$selected_workspace
fi
