#!/usr/bin/env bash

###################################################################
#Script Name	: changeMonitor
#Description	: simple script that handles different monitor configuration
#Args         	: type of configuration
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 23/1/2020
###################################################################

helpMessage="usage: changeMonitor<monitor configuration>
    \n\npossible configuration
    \n\t eDP1:    only laptop
    \n\t DP1Up: VGA up
    \n\t hdmiUp:  hdmiUP
    \n\t hdmi:    only hdmi
    "

[ -z $1 ] && echo -e $helpMessage && exit

configuration=$1

case "$configuration" in
    DP1Up)
        xrandr --output eDP1 --auto --primary \
            --output DP1 --auto --above eDP1 \
            --output HMDI1 --off
        monitorHandler
        ;;
    hdmiUp)
        xrandr --output eDP1 --auto --primary \
            --output HDMI1 --auto --above eDP1 \
            --output DP1 --off
        monitorHandler
        ;;
    hdmi)
        xrandr --output eDP1 --off \
            --output HDMI1 --auto --primary \
            --output DP1 --off
        monitorHandler
        ;;
    eDP1)
        xrandr --output eDP1 --auto --primary \
            --output HDMI1 --off \
            --output DP1 --off
        monitorHandler
        ;;
    *)
        echo -e $helpMessage
        exit
esac
pkill lemonblocks -3
