#!/usr/bin/env bash

###################################################################
#Script Name	: launchAutorename
#Description	: kill al autorenameScript that is running
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

# Terminate already running autorenameNodes instances
killall -q autorenameNodes

# Wait until the processes have been shut down
while pgrep -u $UID -x autorenameNodes >/dev/null; do sleep 1; done

# Launch autorenameNodes script
autorenameNodes &
