#!/usr/bin/env bash

###################################################################
#Script Name	: launchePolybar
#Description	: kill all instances of polybar and run it
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# while ps -A | grep polybar >/dev/null; do sleep 1; done

# Launch bar1
polybar bar1 -c /home/fedeizzo/.config/polybar/config &
