#!/usr/bin/env bash

###################################################################
#Script Name	: launchPicom
#Description	: kill all picom istances and run it
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

# Terminate already running picom istances
killall -q bspwmbar

# Wait until the processes have been shut down
while pgrep -u $UID -x bspwmbar >/dev/null; do sleep 1; done

bspwmbar &
disown %bspwmbar
