#!/usr/bin/env bash

cmd=$1
amount=$2

[ -z $cmd ] && echo "Command needed" && exit

case $cmd in
    "make")
        [ -z $amount ] && echo "Amount needed" && exit 1
        sudo fallocate -l $amount"G" /swap/tmp_swap
        sudo chmod 600 /swap/tmp_swap
        sudo mkswap /swap/tmp_swap
        sudo swapon /swap/tmp_swap
        ;;
    "delete")
        sudo swapoff /swap/tmp_swap
        sudo rm /swap/tmp_swap
        ;;
    *)
        echo "No command $cmd"
esac
exit 0
