#!/usr/bin/env bash

###################################################################
#Script Name	: monitorQuery
#Description	: gives info about plugged monitors
#Args         	: monitor name
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 26-02-2020
###################################################################

helpMessage="usage: monitorQuery <monitor name> \n\t possible value {hdmi, hdmiPrimary, dp1}"

[ -z $1 ] && echo -e $helpMessage && exit

monitor=$1
case "$monitor" in
    hdmiPrimary)
        query=$(xrandr -q | grep HDMI1 | awk '{print $3}')
        echo $query
        ;;
    hdmi)
        query=$(xrandr -q | grep HDMI1 | awk '{print $2}')
        echo $query
        ;;
    dp1)
        query=$(xrandr -q | grep '^DP1' | awk '{print $2}')
        echo $query
        ;;
    edp1)
        query=$(xrandr -q | grep 'eDP1' | awk '{print $2}')
        echo $query
        ;;
    *)
        echo -e $helpMessage
        ;;
esac
