#!/usr/bin/env bash
swaymsg -t get_tree &> /dev/null
last_cmd=$?
set -e
if [[ $last_cmd == 0 ]]; then
    selected_workspace=$(swaymsg -t get_workspaces -r | jq -M '.[] | select(.focused==false) | .name' | tr -d '"' | rofi -dmenu)
    swaymsg move workspace $selected_workspace
    if [[ $1 == '-m' ]]; then
	swaymsg workspace $selected_workspace
    fi
else
    selected_workspace=$(hyprctl workspaces | sed '/\(^\t.*\|^$\)/d' | awk -F '[()]' '{print $(NF-1)}' | rofi -dmenu)
    hyprctl dispatch movetoworkspacesilent name:$selected_workspace
fi
