#!/usr/bin/env bash

chosen=$(echo -e "Suspend\nLock\nShutdown\nReboot" | rofi -dmenu -i -p "")

if [[ $chosen = "Shutdown" ]]; then
	systemctl poweroff
elif [[ $chosen = "Lock" ]]; then
    betterlockscreen -l
elif [[ $chosen = "Reboot" ]]; then
	systemctl reboot
elif [[ $chosen = "Suspend" ]]; then
	systemctl suspend
fi
