#!/usr/bin/env bash
set -e
st -c rbwAutofill /home/fedeizzo/.sources/rbwGetPassword
request=$(cat /tmp/rbwAutofillRequest)
rm /tmp/rbwAutofillRequest
pass=$(rbw get $request)
sleep 0.1
xdotool type --window $(xdotool getactivewindow) --clearmodifiers "$pass"
