#!/usr/bin/env bash

###################################################################
#Script Name	: smartFocus
#Description	: smart focus for bspwm for multimonitor
#Args         	: option, monitor and desktop
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

monitorHdmi=$(xrandr -q | grep HDMI1 | awk '{print $2}')
isHdmiPrimary=$(xrandr -q | grep HDMI1 | awk '{print $3}')
monitorDp1=$(xrandr -q | grep '^DP1' | awk '{print $2}')

option=$1
monitor=$2
desktop=$3

case "$option" in
    --focus|-f)
        if [[ $monitorHdmi == "connected" && $monitor == "second" ]]
        then
            bspc desktop -f HDMI1:\^$desktop
        elif [[ $monitorDp1 == "connected" && $monitor == "second" ]]
        then
            bspc desktop -f DP1:\^$desktop
        elif [[ $isHdmiPrimary != "primary" && $monitor == "first" ]]
        then
            bspc desktop -f eDP1:\^$desktop
        fi
        ;;
    --send|-s)
        if [[ $monitorHdmi == "connected" && $monitor == "second" ]]
        then
            bspc node -d HDMI1:\^$desktop
        elif [[ $monitorDp1 == "connected" && $monitor == "second" ]]
        then
            bspc node -d DP1:\^$desktop
        elif [[ $isHdmiPrimary != "primary" && $monitor == "first" ]]
        then
            bspc node -d eDP1:\^$desktop
        fi
        ;;
    --sendFollow|-sf)
        if [[ $monitorHdmi == "connected" && $monitor == "second" ]]
        then
            bspc node -d HDMI1:\^$desktop -f
        elif [[ $monitorDp1 == "connected" && $monitor == "second" ]]
        then
            bspc node -d DP1:\^$desktop -f
        elif [[ $isHdmiPrimary != "primary" && $monitor == "first" ]]
        then
            bspc node -d eDP1:\^$desktop -f
        fi
        ;;
esac
pkill lemonblocks -3
