#!/usr/bin/env bash

for f in $(chezmoi managed); do
    if [[ $(chezmoi verify $f) == 0 ]]; then
        echo "updated"
    fi
    if [[ $(chezmoi verify $f) == 0 ]]; then
        echo "not updated"
    fi
done
