#!/usr/bin/env bash

###################################################################
#Script Name	: yt
#Description	: (orrible :))script to learn some bash scripting
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

videos=$(mktemp -t yt.XXXXXX)
ids=$(mktemp -t yt.XXXXXX)
urls=$(mktemp -t yt.XXXXXX)
title=$(mktemp -t yt.XXXXXX)
imageDir=$(mktemp -t -d)
youtube-viewer --no-interactive -SV > $videos
sed -i 1d $videos
awk -F "[{}]" '{print $1}' < $videos > $title
awk -F "[{}]" '{print $2}' < $videos > $ids
awk -F "[{}]" '{print $4}' < $videos > $urls
counter=1
while read line
do
    imagePath=$imageDir'/'$counter
    wget https://img.youtube.com/vi/$line/default.jpg -q -O $imagePath.jpg
    counter=$((counter + 1))
done < $ids
clear
for i in {1..10}
do
    content=$(sed -n "$i p" $title)
    content2=$(sed -n "$((i + 10)) p" $title)
    printf '\n\n'
    printf '\t\t'
    echo $content
    printf '\t\t\t\t\t\t\t\t\t\t\t\t\t'
    echo $content2
    printf '\n'
done
printf '\npress key then insert number'
function draw {
    source "`ueberzug library`"
    ImageLayer 0< <(
    ImageLayer::add [identifier]="0" [x]="0" [y]="0" [max_width]="20" [max_height]="20" [path]="$imageDir/1.jpg"
    ImageLayer::add [identifier]="1" [x]="0" [y]="5" [max_width]="20" [max_height]="20" [path]="$imageDir/2.jpg"
    ImageLayer::add [identifier]="2" [x]="0" [y]="10" [max_width]="20" [max_height]="20" [path]="$imageDir/3.jpg"
    ImageLayer::add [identifier]="3" [x]="0" [y]="15" [max_width]="20" [max_height]="20" [path]="$imageDir/4.jpg"
    ImageLayer::add [identifier]="4" [x]="0" [y]="20" [max_width]="20" [max_height]="20" [path]="$imageDir/5.jpg"
    ImageLayer::add [identifier]="5" [x]="0" [y]="25" [max_width]="20" [max_height]="20" [path]="$imageDir/6.jpg"
    ImageLayer::add [identifier]="6" [x]="0" [y]="30" [max_width]="20" [max_height]="20" [path]="$imageDir/7.jpg"
    ImageLayer::add [identifier]="7" [x]="0" [y]="35" [max_width]="20" [max_height]="20" [path]="$imageDir/8.jpg"
    ImageLayer::add [identifier]="8" [x]="0" [y]="40" [max_width]="20" [max_height]="20" [path]="$imageDir/9.jpg"
    ImageLayer::add [identifier]="9" [x]="0" [y]="45" [max_width]="20" [max_height]="20" [path]="$imageDir/10.jpg"
    ImageLayer::add [identifier]="10" [x]="90" [y]="0" [max_width]="20" [max_height]="20" [path]="$imageDir/11.jpg"
    ImageLayer::add [identifier]="11" [x]="90" [y]="5" [max_width]="20" [max_height]="20" [path]="$imageDir/12.jpg"
    ImageLayer::add [identifier]="12" [x]="90" [y]="10" [max_width]="20" [max_height]="20" [path]="$imageDir/13.jpg"
    ImageLayer::add [identifier]="13" [x]="90" [y]="15" [max_width]="20" [max_height]="20" [path]="$imageDir/14.jpg"
    ImageLayer::add [identifier]="14" [x]="90" [y]="20" [max_width]="20" [max_height]="20" [path]="$imageDir/15.jpg"
    ImageLayer::add [identifier]="15" [x]="90" [y]="25" [max_width]="20" [max_height]="20" [path]="$imageDir/16.jpg"
    ImageLayer::add [identifier]="16" [x]="90" [y]="30" [max_width]="20" [max_height]="20" [path]="$imageDir/17.jpg"
    ImageLayer::add [identifier]="17" [x]="90" [y]="35" [max_width]="20" [max_height]="20" [path]="$imageDir/18.jpg"
    ImageLayer::add [identifier]="18" [x]="90" [y]="40" [max_width]="20" [max_height]="20" [path]="$imageDir/19.jpg"
    ImageLayer::add [identifier]="19" [x]="90" [y]="45" [max_width]="20" [max_height]="20" [path]="$imageDir/20.jpg"
    read
    )
}
draw
rm $videos
rm $ids
rm $title
read video
while [[ "$video" != "q" ]]
do
    url=$(sed -n "$video p" $urls)
    vlc --play-and-exit $url
    draw
    printf '\ninsert number(q for quit): '
    read video
done
rm -r $imageDir
rm $urls
