#!/usr/bin/env bash
function backup_info {
    systemctl status borgbackup-job-$1-persistent.service | grep 'Active: active' > /dev/null
    if [[ $? == 0 ]]; then
	status=""
	echo '{"text":"'$status'","class":"borg-backup-doing"}'
    else
	last_backup=$(systemctl list-timers | grep borgbackup-job-$1-persistent.service | awk -F' ' '{print $8" "$9}' | date +%s -f -)
	error_retriving_last_backup=$?
	now=$(date '+%s')
	diff=$((now-last_home_backup))

        # 7200 seconds are 2 hours
	if [[ $diff > 7200 || $error_retriving_last_backup != 0 ]]; then
	    status=""
	    echo '{"text":"'$status'","class":"borg-backup-error"}'
	else
	    status=""
	    echo '{"text":"'$status'","class":"borg-backup"}'
	fi
    fi
}

[ -z $1 ] && echo "usage $0 <backup_type> available types are root and home" && exit 1

backup_info $1
