#!/usr/bin/env bash
swaymsg -t get_tree &> /dev/null
if [[ $? == 0 ]]; then
    selected_workspace=$(swaymsg -t get_workspaces -r | jq -M '.[] | select(.focused==false and .visible==false) | .name' | tr -d '"' | rofi -dmenu)
    current_output=$(swaymsg -t get_outputs --raw | jq '. | map(select(.focused == true)) | .[0].name' -r)
    if [[ $? != 0 ]]; then
	exit 1
    fi

    swaymsg "[workspace=${selected_workspace}]" move workspace to output "${current_output}"
    swaymsg workspace $selected_workspace
else
    set -e
    monitors=$(hyprctl monitors -j )
    workspaces=$(hyprctl workspaces -j)
    focused_monitor=$(echo $monitors | hyprctl -j monitors | jq -r 'map(.focused == true) | index(true)')
    selected_workspace=$(echo $workspaces | jq -r '.[] | select(.name != "special") |.name' | rofi -dmenu)
    hyprctl dispatch moveworkspacetomonitor name:$selected_workspace $focused_monitor
    hyprctl dispatch workspace name:$selected_workspace
fi
