#!/usr/bin/env bash

###################################################################
#Script Name	: cheat
#Description	: see some example of most common commmand
#Args         	: command name
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

helpMessage="usage: cheat <command name>"

[ -z $1 ] && echo -e $helpMessage && exit
curl -s cheat.sh/$1
