#!/usr/bin/env bash
hyprctl clients | grep "specialkitty" &> /dev/null
if [[ $? != 0 ]]; then
    hyprctl keyword windowrulev2 "workspace special silent,class:^(specialkitty)$"
    hyprctl dispatch exec "kitty --class specialkitty"
fi
