#!/usr/bin/env bash

if [[ -z $1 ]]; then
  monitors=$(hyprctl monitors -j | jq -r '.[] | .name')
  hyprctl dispatch swapactiveworkspaces $monitors
else
  workspace=$1
fi


focused_monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')
unfocused_montitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused == false) | .activeWorkspace | .id')
focused_workspace=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .activeWorkspace | .id')
unfocused_workspace=$(hyprctl monitors -j | jq -r '.[] | select(.focused == false) | .activeWorkspace | .id')

if [[ $focused_workspace != $workspace ]]; then
    if [[ $unfocused_workspace == $workspace ]]; then
	monitors=$(hyprctl monitors -j | jq -r '.[] | .name')
	hyprctl dispatch swapactiveworkspaces $monitors
    else
	hyprctl dispatch moveworkspacetomonitor $workspace $focused_monitor
	hyprctl dispatch workspace $workspace
	hyprctl dispatch focusmonitor $focused_monitor
    fi
fi
exit 0
