#!/usr/bin/env bash
# export SDL_VIDEODRIVER=wayland
# export _JAVA_AWT_WM_NONREPARENTING=1
# export QT_QPA_PLATFORM=wayland
# export XDG_SESSION_DESKTOP=hyprland
# export XDG_CURRENT_DESKTOP=Unity
# export XDG_SESSION_TYPE="wayland"
# export GTK_USE_PORTAL=0
# export MOZ_ENABLE_WAYLAND=1
source $HOME/.xprofile
systemctl --user import-environment
Hyprland
