#!/usr/bin/env bash

###################################################################
#Script Name	: makePDF
#Description	: take input md file and create pdf with latex layout
#Args         	: name of md file
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

helpMessage="usage: makePDF <name file>"

[ -z $1 ] && echo -e $helpMessage && exit

position=$(pwd)
path=$position'/*.md'
name=$1
newName=$(echo $name | sed -r 's/\.md/\.pdf/g')
pandoc $path -s -t latex | tectonic - -o $position 2> /dev/null && mv texput.pdf $newName
