#!/usr/bin/env bash
swaymsg -t get_tree &> /dev/null
if [[ $? == 0 ]]; then
    output_1_name=$(swaymsg -t get_outputs --raw | jq '.[0].name' -r)
    output_2_name=$(swaymsg -t get_outputs --raw | jq '.[1].name' -r)
    workspace_on_1=$(swaymsg -t get_outputs --raw | jq '.[0].current_workspace' -r)
    workspace_on_2=$(swaymsg -t get_outputs --raw | jq '.[1].current_workspace' -r)

    swaymsg workspace $workspace_on_2
    swaymsg move workspace to output $output_1_name
    swaymsg workspace $workspace_on_1
    swaymsg move workspace to output $output_2_name
else
    output_0_name=$(hyprctl -j monitors | jq -r '.[0].activeWorkspace.name')
    is_0_focused=$(hyprctl -j monitors | jq -r '.[0].focused')
    output_1_name=$(hyprctl -j monitors | jq -r '.[1].activeWorkspace.name')
    is_1_focused=$(hyprctl -j monitors | jq -r '.[0].focused')
    if [[ $is_0_focused == "true" ]]; then
	hyprctl dispatch moveworkspacetomonitor name:$output_0_name 1
	hyprctl dispatch workspace name:$output_0_name
	hyprctl dispatch moveworkspacetomonitor name:$output_1_name 0
	hyprctl dispatch workspace name:$output_1_name
    else
	hyprctl dispatch moveworkspacetomonitor name:$output_1_name 0
	hyprctl dispatch workspace name:$output_1_name
	hyprctl dispatch moveworkspacetomonitor name:$output_0_name 1
	hyprctl dispatch workspace name:$output_0_name
    fi
fi
