apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fedeizzo-dev
  namespace: default
spec:
  secretName: fedeizzo-dev-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.fedeizzo.dev"
  dnsNames:
    - "fedeizzo.dev"
    - "*.fedeizzo.dev"
