// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"pan/internal/fastmail"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddTagToEmail provides a mock function for the type MockService
func (_mock *MockService) AddTagToEmail(ctx context.Context, emailID string, tag fastmail.Tag) error {
	ret := _mock.Called(ctx, emailID, tag)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, fastmail.Tag) error); ok {
		r0 = returnFunc(ctx, emailID, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddTagToEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToEmail'
type MockService_AddTagToEmail_Call struct {
	*mock.Call
}

// AddTagToEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - emailID string
//   - tag fastmail.Tag
func (_e *MockService_Expecter) AddTagToEmail(ctx interface{}, emailID interface{}, tag interface{}) *MockService_AddTagToEmail_Call {
	return &MockService_AddTagToEmail_Call{Call: _e.mock.On("AddTagToEmail", ctx, emailID, tag)}
}

func (_c *MockService_AddTagToEmail_Call) Run(run func(ctx context.Context, emailID string, tag fastmail.Tag)) *MockService_AddTagToEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fastmail.Tag
		if args[2] != nil {
			arg2 = args[2].(fastmail.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddTagToEmail_Call) Return(err error) *MockService_AddTagToEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddTagToEmail_Call) RunAndReturn(run func(ctx context.Context, emailID string, tag fastmail.Tag) error) *MockService_AddTagToEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function for the type MockService
func (_mock *MockService) GetTags(ctx context.Context) ([]fastmail.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []fastmail.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]fastmail.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []fastmail.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fastmail.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockService_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetTags(ctx interface{}) *MockService_GetTags_Call {
	return &MockService_GetTags_Call{Call: _e.mock.On("GetTags", ctx)}
}

func (_c *MockService_GetTags_Call) Run(run func(ctx context.Context)) *MockService_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetTags_Call) Return(tags []fastmail.Tag, err error) *MockService_GetTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockService_GetTags_Call) RunAndReturn(run func(ctx context.Context) ([]fastmail.Tag, error)) *MockService_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadEmailForTag provides a mock function for the type MockService
func (_mock *MockService) GetUnreadEmailForTag(ctx context.Context, tag fastmail.Tag) (*fastmail.Email, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadEmailForTag")
	}

	var r0 *fastmail.Email
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, fastmail.Tag) (*fastmail.Email, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, fastmail.Tag) *fastmail.Email); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fastmail.Email)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, fastmail.Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUnreadEmailForTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadEmailForTag'
type MockService_GetUnreadEmailForTag_Call struct {
	*mock.Call
}

// GetUnreadEmailForTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag fastmail.Tag
func (_e *MockService_Expecter) GetUnreadEmailForTag(ctx interface{}, tag interface{}) *MockService_GetUnreadEmailForTag_Call {
	return &MockService_GetUnreadEmailForTag_Call{Call: _e.mock.On("GetUnreadEmailForTag", ctx, tag)}
}

func (_c *MockService_GetUnreadEmailForTag_Call) Run(run func(ctx context.Context, tag fastmail.Tag)) *MockService_GetUnreadEmailForTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fastmail.Tag
		if args[1] != nil {
			arg1 = args[1].(fastmail.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUnreadEmailForTag_Call) Return(email *fastmail.Email, err error) *MockService_GetUnreadEmailForTag_Call {
	_c.Call.Return(email, err)
	return _c
}

func (_c *MockService_GetUnreadEmailForTag_Call) RunAndReturn(run func(ctx context.Context, tag fastmail.Tag) (*fastmail.Email, error)) *MockService_GetUnreadEmailForTag_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailAsSeen provides a mock function for the type MockService
func (_mock *MockService) MarkEmailAsSeen(ctx context.Context, emailID string) error {
	ret := _mock.Called(ctx, emailID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailAsSeen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, emailID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkEmailAsSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailAsSeen'
type MockService_MarkEmailAsSeen_Call struct {
	*mock.Call
}

// MarkEmailAsSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - emailID string
func (_e *MockService_Expecter) MarkEmailAsSeen(ctx interface{}, emailID interface{}) *MockService_MarkEmailAsSeen_Call {
	return &MockService_MarkEmailAsSeen_Call{Call: _e.mock.On("MarkEmailAsSeen", ctx, emailID)}
}

func (_c *MockService_MarkEmailAsSeen_Call) Run(run func(ctx context.Context, emailID string)) *MockService_MarkEmailAsSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MarkEmailAsSeen_Call) Return(err error) *MockService_MarkEmailAsSeen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkEmailAsSeen_Call) RunAndReturn(run func(ctx context.Context, emailID string) error) *MockService_MarkEmailAsSeen_Call {
	_c.Call.Return(run)
	return _c
}
