// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"git.sr.ht/~rockorager/go-jmap"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJMAPClient creates a new instance of MockJMAPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJMAPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJMAPClient {
	mock := &MockJMAPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJMAPClient is an autogenerated mock type for the JMAPClient type
type MockJMAPClient struct {
	mock.Mock
}

type MockJMAPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJMAPClient) EXPECT() *MockJMAPClient_Expecter {
	return &MockJMAPClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockJMAPClient
func (_mock *MockJMAPClient) Do(req *jmap.Request) (*jmap.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *jmap.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jmap.Request) (*jmap.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*jmap.Request) *jmap.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jmap.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*jmap.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJMAPClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockJMAPClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *jmap.Request
func (_e *MockJMAPClient_Expecter) Do(req interface{}) *MockJMAPClient_Do_Call {
	return &MockJMAPClient_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockJMAPClient_Do_Call) Run(run func(req *jmap.Request)) *MockJMAPClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jmap.Request
		if args[0] != nil {
			arg0 = args[0].(*jmap.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJMAPClient_Do_Call) Return(response *jmap.Response, err error) *MockJMAPClient_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockJMAPClient_Do_Call) RunAndReturn(run func(req *jmap.Request) (*jmap.Response, error)) *MockJMAPClient_Do_Call {
	_c.Call.Return(run)
	return _c
}
