keys:
  - &laptop age162fef9eha0za3r97qk7jaw7y87wlj5lgzl8laqemagqsftq7693sckrcc6
  - &raspberry age14jd2uvg5fwc2r2vgp4tsw5dy9rpksel97um2v494ws4tptult9ys50cndr
  - &mac age1pcxugka7t0awheru3nvlsylveczcyqy63dtwa8jygph39jces50sqlljw3
creation_rules:
  - path_regex: laptop-secrets.yaml$
    key_groups:
    - age:
      - *laptop
  - path_regex: raspberry-secrets.yaml$
    key_groups:
    - age:
      - *raspberry
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *laptop
      - *raspberry
