keys:
  - &oven age13wm6jg6enxyuapu23xn522avfgre8fesh3w8qzn3lyukf5u7fy8sxdesvu
  - &homelab age14jd2uvg5fwc2r2vgp4tsw5dy9rpksel97um2v494ws4tptult9ys50cndr
creation_rules:
  - path_regex: .*oven-secrets.*$
    key_groups:
    - age:
      - *oven
  - path_regex: .*homelab-secrets.*$
    key_groups:
    - age:
      - *homelab
