* NixOS personal configuration
Full nixos configuration for following devices:
- Dell XPS 9510
- Thinkpad X1 Carbon 6th gen
- Raspberry pi
- Macbook pro M1 Max

Folder description:
- home: contains home manager configurations.
- hosts: contains nixos system wide configurations.
- lib: some useful function definitions.
- modules: self explanatory.
- overlays: self explanatory.
- pkgs: custom derivations.
- qmk_config: keyboard configurations.
- secrets: [[https://github.com/Mic92/sops-nix][sops-nix]] secrets.
- templates: flakes templates.
  
** Fresh install
*** Thinkpad X1 Carbon 6th gen
#+begin_src sh
  sudo nix run 'github:nix-community/disko#disko-install' -- --flake github.com/fedeizzo/nix-dotfiles.go#oven
#+end_src

*** Dell xps 9510
Partitioning is made with ~btrfs~ file system, during it two blank read-only snapshots are taken:
- ~root~
- ~home~

It can be done with the following script:
#+begin_src sh
  ./scripts/installation/xps-9510.sh
  # reboot
  ./scripts/installation/xps-9510.sh --complete
#+end_src

Snapshots are used to erase the disk at every boot in order to obtain a complete immutable and declarative system.

Obviously some data, logs, cache, etc. must survive the boot process, this is achieved using [[https://github.com/nix-community/impermanence][imperamanence]].

Some useful readings if you are interested:
- [[https://mt-caret.github.io/blog/posts/2020-06-29-optin-state.html][erase with btrfs snapshot]]
- [[https://grahamc.com/blog/erase-your-darlings][erase with zfs]]
- [[https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/][erase with tmpfs]]
- [[https://elis.nu/blog/2020/06/nixos-tmpfs-as-home/][erase home]]

*** Raspberry
Raspberry is formatted with ext4 as filesystem.
#+begin_src sh
  ./scripts/installation/raspberry.sh
#+end_src

*** Macbook-pro
#+begin_src sh
  nix run nix-darwin -- switch --flake .
#+end_src

** Keyboards
[[file:./qmk_config/README.org][QMK keyboard firmware]]
