#!/usr/bin/env bash
function backup_info {
    systemctl status borgbackup-job-$1-persistent.service | grep 'Active: active' > /dev/null
    if [[ $? == 0 ]]; then
	status=""
	echo '{"text":"'$status'","class":"borg-backup-doing"}'
    else
	status=""
	echo '{"text":"'$status'","class":"borg-backup"}'
    fi
}

[ -z $1 ] && echo "usage $0 <backup_type> available types are root and home" && exit 1

backup_info $1
