#!/usr/bin/env bash

temp_dir=$(mktemp -d)
cd $temp_dir
cp $HOME/.config/inkscape-helper/latex_template.tex main.tex
$EDITOR main.tex
pdflatex main.tex &> /dev/null
pdf2svg main.pdf main.svg
cat main.svg | wl-copy
rm -r $temp_dir
