// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fastmail

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFastmailService creates a new instance of MockFastmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFastmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFastmailService {
	mock := &MockFastmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFastmailService is an autogenerated mock type for the FastmailService type
type MockFastmailService struct {
	mock.Mock
}

type MockFastmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFastmailService) EXPECT() *MockFastmailService_Expecter {
	return &MockFastmailService_Expecter{mock: &_m.Mock}
}

// AddTagToEmail provides a mock function for the type MockFastmailService
func (_mock *MockFastmailService) AddTagToEmail(ctx context.Context, emailID string, tag Tag) error {
	ret := _mock.Called(ctx, emailID, tag)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, Tag) error); ok {
		r0 = returnFunc(ctx, emailID, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFastmailService_AddTagToEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToEmail'
type MockFastmailService_AddTagToEmail_Call struct {
	*mock.Call
}

// AddTagToEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - emailID string
//   - tag Tag
func (_e *MockFastmailService_Expecter) AddTagToEmail(ctx interface{}, emailID interface{}, tag interface{}) *MockFastmailService_AddTagToEmail_Call {
	return &MockFastmailService_AddTagToEmail_Call{Call: _e.mock.On("AddTagToEmail", ctx, emailID, tag)}
}

func (_c *MockFastmailService_AddTagToEmail_Call) Run(run func(ctx context.Context, emailID string, tag Tag)) *MockFastmailService_AddTagToEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Tag
		if args[2] != nil {
			arg2 = args[2].(Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFastmailService_AddTagToEmail_Call) Return(err error) *MockFastmailService_AddTagToEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFastmailService_AddTagToEmail_Call) RunAndReturn(run func(ctx context.Context, emailID string, tag Tag) error) *MockFastmailService_AddTagToEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function for the type MockFastmailService
func (_mock *MockFastmailService) GetTags(ctx context.Context) ([]Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFastmailService_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockFastmailService_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFastmailService_Expecter) GetTags(ctx interface{}) *MockFastmailService_GetTags_Call {
	return &MockFastmailService_GetTags_Call{Call: _e.mock.On("GetTags", ctx)}
}

func (_c *MockFastmailService_GetTags_Call) Run(run func(ctx context.Context)) *MockFastmailService_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFastmailService_GetTags_Call) Return(tags []Tag, err error) *MockFastmailService_GetTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockFastmailService_GetTags_Call) RunAndReturn(run func(ctx context.Context) ([]Tag, error)) *MockFastmailService_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadEmailForTag provides a mock function for the type MockFastmailService
func (_mock *MockFastmailService) GetUnreadEmailForTag(ctx context.Context, tag Tag) (*Email, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadEmailForTag")
	}

	var r0 *Email
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tag) (*Email, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tag) *Email); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Email)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFastmailService_GetUnreadEmailForTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadEmailForTag'
type MockFastmailService_GetUnreadEmailForTag_Call struct {
	*mock.Call
}

// GetUnreadEmailForTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag Tag
func (_e *MockFastmailService_Expecter) GetUnreadEmailForTag(ctx interface{}, tag interface{}) *MockFastmailService_GetUnreadEmailForTag_Call {
	return &MockFastmailService_GetUnreadEmailForTag_Call{Call: _e.mock.On("GetUnreadEmailForTag", ctx, tag)}
}

func (_c *MockFastmailService_GetUnreadEmailForTag_Call) Run(run func(ctx context.Context, tag Tag)) *MockFastmailService_GetUnreadEmailForTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Tag
		if args[1] != nil {
			arg1 = args[1].(Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFastmailService_GetUnreadEmailForTag_Call) Return(email *Email, err error) *MockFastmailService_GetUnreadEmailForTag_Call {
	_c.Call.Return(email, err)
	return _c
}

func (_c *MockFastmailService_GetUnreadEmailForTag_Call) RunAndReturn(run func(ctx context.Context, tag Tag) (*Email, error)) *MockFastmailService_GetUnreadEmailForTag_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailAsSeen provides a mock function for the type MockFastmailService
func (_mock *MockFastmailService) MarkEmailAsSeen(ctx context.Context, emailID string) error {
	ret := _mock.Called(ctx, emailID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailAsSeen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, emailID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFastmailService_MarkEmailAsSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailAsSeen'
type MockFastmailService_MarkEmailAsSeen_Call struct {
	*mock.Call
}

// MarkEmailAsSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - emailID string
func (_e *MockFastmailService_Expecter) MarkEmailAsSeen(ctx interface{}, emailID interface{}) *MockFastmailService_MarkEmailAsSeen_Call {
	return &MockFastmailService_MarkEmailAsSeen_Call{Call: _e.mock.On("MarkEmailAsSeen", ctx, emailID)}
}

func (_c *MockFastmailService_MarkEmailAsSeen_Call) Run(run func(ctx context.Context, emailID string)) *MockFastmailService_MarkEmailAsSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFastmailService_MarkEmailAsSeen_Call) Return(err error) *MockFastmailService_MarkEmailAsSeen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFastmailService_MarkEmailAsSeen_Call) RunAndReturn(run func(ctx context.Context, emailID string) error) *MockFastmailService_MarkEmailAsSeen_Call {
	_c.Call.Return(run)
	return _c
}
