apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      volumes:
      - name: homer-config
        hostPath:
          path: /var/volumes/homer-config
      containers:
      - name: homer
        image: b4bz/homer:v22.08.1
        ports:
        - containerPort: 8080
        volumeMounts
        - name: homer-config
          mountPath: /www/assets
        env:
        - name: INIT_ASSETS
          value: 1
        - name: PUID
          value: 1000
        - name: PGID
          value: 100
        - name: TZ
          value: "Europe/Rome"
---
apiVersion: v1
kind: Service
metadata:
  name: homer-service
spec:
  selector:
    app: homer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
