apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-monitor
  labels:
    app: rpi-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpi-monitor
  template:
    metadata:
      labels:
        app: rpi-monitor
    spec:
      volumes:
      - name: homer-config
        hostPath:
          path: /var/volumes/homer-config
      containers:
      - name: rpi-monitor
        image: michaelmiklis/rpi-monitor:latest
        ports:
        - containerPort: 8080
        volumeMounts
        - name: homer-config
          mountPath: /www/assets
        env:
        - name: INIT_ASSETS
          value: 1
        - name: PUID
          value: 1000
        - name: PGID
          value: 100
        - name: TZ
          value: "Europe/Rome"
---
apiVersion: v1
kind: Service
metadata:
  name: rpi-monitor-service
spec:
  selector:
    app: rpi-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
