apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      volumes:
      - name: homer-config
        hostPath:
          path: /var/volumes/homer-config
      containers:
      - name: homer
        image: b4bz/homer:v22.08.1
        ports:
        - name: homer-port
          containerPort: 8080
        volumeMounts:
        - name: homer-config
          mountPath: /www/assets
        env:
        - name: INIT_ASSETS
          valueFrom:
            configMapKeyRef:
              name: homer-config
              key: INIT_ASSETS
        # - name: SUBFOLDER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: homer-config
        #       key: SUBFOLDER
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: TZ
---
apiVersion: v1
kind: Service
metadata:
  name: homer-service
spec:
  selector:
    app: homer
  ports:
    - protocol: TCP
      name: homer-port
      port: 80
      targetPort: homer-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer-ingress
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure # to use https globally
  #   traefik.ingress.kubernetes.io/router.tls: "true" # to use htpss when tls is not set globally
  # traefik.ingress.kubernetes.io/service.serversscheme: https # to use https in the comunication between traefik and the service
    # traefik.http.routers.cal.rule: Host(`homer.home-lab`)
    # "traefik.http.routers.cal.entrypoints=web"
spec:
  rules:
  - host: "homer.home-lab"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homer-service
            port:
              name: homer-port
