// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Cidan/lunchmoney-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetCategory provides a mock function for the type MockService
func (_mock *MockService) GetCategory(ctx context.Context, id int32) (*lunchmoney.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *lunchmoney.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*lunchmoney.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *lunchmoney.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lunchmoney.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockService_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockService_Expecter) GetCategory(ctx interface{}, id interface{}) *MockService_GetCategory_Call {
	return &MockService_GetCategory_Call{Call: _e.mock.On("GetCategory", ctx, id)}
}

func (_c *MockService_GetCategory_Call) Run(run func(ctx context.Context, id int32)) *MockService_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCategory_Call) Return(v *lunchmoney.Category, err error) *MockService_GetCategory_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_GetCategory_Call) RunAndReturn(run func(ctx context.Context, id int32) (*lunchmoney.Category, error)) *MockService_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type MockService
func (_mock *MockService) ListCategories(ctx context.Context, params *lunchmoney.ListCategoriesParams) (*lunchmoney.CategoriesListResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 *lunchmoney.CategoriesListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lunchmoney.ListCategoriesParams) (*lunchmoney.CategoriesListResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lunchmoney.ListCategoriesParams) *lunchmoney.CategoriesListResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lunchmoney.CategoriesListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lunchmoney.ListCategoriesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - params *lunchmoney.ListCategoriesParams
func (_e *MockService_Expecter) ListCategories(ctx interface{}, params interface{}) *MockService_ListCategories_Call {
	return &MockService_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, params)}
}

func (_c *MockService_ListCategories_Call) Run(run func(ctx context.Context, params *lunchmoney.ListCategoriesParams)) *MockService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lunchmoney.ListCategoriesParams
		if args[1] != nil {
			arg1 = args[1].(*lunchmoney.ListCategoriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListCategories_Call) Return(categoriesListResponse *lunchmoney.CategoriesListResponse, err error) *MockService_ListCategories_Call {
	_c.Call.Return(categoriesListResponse, err)
	return _c
}

func (_c *MockService_ListCategories_Call) RunAndReturn(run func(ctx context.Context, params *lunchmoney.ListCategoriesParams) (*lunchmoney.CategoriesListResponse, error)) *MockService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type MockService
func (_mock *MockService) ListTags(ctx context.Context) (*lunchmoney.TagsListResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 *lunchmoney.TagsListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*lunchmoney.TagsListResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *lunchmoney.TagsListResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lunchmoney.TagsListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListTags(ctx interface{}) *MockService_ListTags_Call {
	return &MockService_ListTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *MockService_ListTags_Call) Run(run func(ctx context.Context)) *MockService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListTags_Call) Return(tagsListResponse *lunchmoney.TagsListResponse, err error) *MockService_ListTags_Call {
	_c.Call.Return(tagsListResponse, err)
	return _c
}

func (_c *MockService_ListTags_Call) RunAndReturn(run func(ctx context.Context) (*lunchmoney.TagsListResponse, error)) *MockService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function for the type MockService
func (_mock *MockService) ListTransactions(ctx context.Context, params *lunchmoney.ListTransactionsParams) (*lunchmoney.TransactionsListResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 *lunchmoney.TransactionsListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lunchmoney.ListTransactionsParams) (*lunchmoney.TransactionsListResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lunchmoney.ListTransactionsParams) *lunchmoney.TransactionsListResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lunchmoney.TransactionsListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lunchmoney.ListTransactionsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockService_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - params *lunchmoney.ListTransactionsParams
func (_e *MockService_Expecter) ListTransactions(ctx interface{}, params interface{}) *MockService_ListTransactions_Call {
	return &MockService_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, params)}
}

func (_c *MockService_ListTransactions_Call) Run(run func(ctx context.Context, params *lunchmoney.ListTransactionsParams)) *MockService_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lunchmoney.ListTransactionsParams
		if args[1] != nil {
			arg1 = args[1].(*lunchmoney.ListTransactionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListTransactions_Call) Return(transactionsListResponse *lunchmoney.TransactionsListResponse, err error) *MockService_ListTransactions_Call {
	_c.Call.Return(transactionsListResponse, err)
	return _c
}

func (_c *MockService_ListTransactions_Call) RunAndReturn(run func(ctx context.Context, params *lunchmoney.ListTransactionsParams) (*lunchmoney.TransactionsListResponse, error)) *MockService_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function for the type MockService
func (_mock *MockService) UpdateTransaction(ctx context.Context, id int64, body lunchmoney.UpdateTransactionBody) (*lunchmoney.Transaction, error) {
	ret := _mock.Called(ctx, id, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 *lunchmoney.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, lunchmoney.UpdateTransactionBody) (*lunchmoney.Transaction, error)); ok {
		return returnFunc(ctx, id, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, lunchmoney.UpdateTransactionBody) *lunchmoney.Transaction); ok {
		r0 = returnFunc(ctx, id, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lunchmoney.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, lunchmoney.UpdateTransactionBody) error); ok {
		r1 = returnFunc(ctx, id, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type MockService_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - body lunchmoney.UpdateTransactionBody
func (_e *MockService_Expecter) UpdateTransaction(ctx interface{}, id interface{}, body interface{}) *MockService_UpdateTransaction_Call {
	return &MockService_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, id, body)}
}

func (_c *MockService_UpdateTransaction_Call) Run(run func(ctx context.Context, id int64, body lunchmoney.UpdateTransactionBody)) *MockService_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 lunchmoney.UpdateTransactionBody
		if args[2] != nil {
			arg2 = args[2].(lunchmoney.UpdateTransactionBody)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateTransaction_Call) Return(v *lunchmoney.Transaction, err error) *MockService_UpdateTransaction_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_UpdateTransaction_Call) RunAndReturn(run func(ctx context.Context, id int64, body lunchmoney.UpdateTransactionBody) (*lunchmoney.Transaction, error)) *MockService_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}
