#!/usr/bin/env bash
export SOPS_AGE_KEY_FILE=/var/lib/sops/keys.txt

helpMessage="\nusage $0: <command>\n\ncommand:\n\tall: apply and delete everything\n\tapply: apply\n\tdelete: delete\n\tsetup: first setup"
[ -z $1 ] && echo -e $helpMessage && exit 1

first_setup() {
    # kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.8/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
    # kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.8/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
    echo "First setup..."
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
    helm install cert-manager jetstack/cert-manager \
	 --namespace cert-manager \
	 --version v1.9.1 \
	 --create-namespace \
	 --set installCRDs=true \
	 --set podDnsPolicy=None \
	 --set 'podDnsConfig.nameservers={1.1.1.1,9.9.9.9}' \
         --set 'extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=1.1.1.1:53\,9.9.9.9:53}'
}

execute_step () {
   echo "$2 operation on file matching regex $1"
   find /etc/homelab-kubernetes -type l -name "*${1}*" | sort | xargs -I sub k3s kubectl $2 -f sub
}

execute_secrets_step () {
   echo "$2 operation on file matching regex $1"
   for file in $(find /etc/homelab-kubernetes -type l -name "*${1}*" | sort); do
       @sops@ --decrypt $file | kubectl $2 -f -
   done
}

case $1 in
    "all")
	execute_secrets_step "sops-app" "apply"
	execute_step "apply" "apply"
	execute_secrets_step "sops-del" "delete"
	execute_step "delete" "delete"
	shift
	;;
    "apply")
	execute_secrets_step "sops-app" "apply"
	execute_step "apply" "apply"
	shift
	;;
    "delete")
	execute_secrets_step "sops-del" "delete"
	execute_step "delete" "delete"
	shift
	;;
    "down")
	execute_step "" "delete"
	shift
	;;
    "setup")
	first_setup
	shift
	;;
    *)
	echo -e "\ncommand $1 not implemented\n"
	echo -e $helpMessage
	;;
esac
