// Code generated by mockery v2.53.6. DO NOT EDIT.

package scheduler

import (
	context "context"
	iter "iter"

	id "maunium.net/go/mautrix/id"

	mock "github.com/stretchr/testify/mock"

	session "google.golang.org/adk/session"
)

// MockBroadcaster is an autogenerated mock type for the Broadcaster type
type MockBroadcaster struct {
	mock.Mock
}

type MockBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcaster) EXPECT() *MockBroadcaster_Expecter {
	return &MockBroadcaster_Expecter{mock: &_m.Mock}
}

// BroadcastStream provides a mock function with given fields: ctx, roomID, eventID, sessionID, stream
func (_m *MockBroadcaster) BroadcastStream(ctx context.Context, roomID id.RoomID, eventID id.EventID, sessionID string, stream iter.Seq2[*session.Event, error]) {
	_m.Called(ctx, roomID, eventID, sessionID, stream)
}

// MockBroadcaster_BroadcastStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastStream'
type MockBroadcaster_BroadcastStream_Call struct {
	*mock.Call
}

// BroadcastStream is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID id.RoomID
//   - eventID id.EventID
//   - sessionID string
//   - stream iter.Seq2[*session.Event,error]
func (_e *MockBroadcaster_Expecter) BroadcastStream(ctx interface{}, roomID interface{}, eventID interface{}, sessionID interface{}, stream interface{}) *MockBroadcaster_BroadcastStream_Call {
	return &MockBroadcaster_BroadcastStream_Call{Call: _e.mock.On("BroadcastStream", ctx, roomID, eventID, sessionID, stream)}
}

func (_c *MockBroadcaster_BroadcastStream_Call) Run(run func(ctx context.Context, roomID id.RoomID, eventID id.EventID, sessionID string, stream iter.Seq2[*session.Event, error])) *MockBroadcaster_BroadcastStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.RoomID), args[2].(id.EventID), args[3].(string), args[4].(iter.Seq2[*session.Event, error]))
	})
	return _c
}

func (_c *MockBroadcaster_BroadcastStream_Call) Return() *MockBroadcaster_BroadcastStream_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcaster_BroadcastStream_Call) RunAndReturn(run func(context.Context, id.RoomID, id.EventID, string, iter.Seq2[*session.Event, error])) *MockBroadcaster_BroadcastStream_Call {
	_c.Run(run)
	return _c
}

// StartJobSession provides a mock function with given fields: ctx, roomID, message
func (_m *MockBroadcaster) StartJobSession(ctx context.Context, roomID id.RoomID, message string) (id.EventID, error) {
	ret := _m.Called(ctx, roomID, message)

	if len(ret) == 0 {
		panic("no return value specified for StartJobSession")
	}

	var r0 id.EventID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, id.RoomID, string) (id.EventID, error)); ok {
		return rf(ctx, roomID, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, id.RoomID, string) id.EventID); ok {
		r0 = rf(ctx, roomID, message)
	} else {
		r0 = ret.Get(0).(id.EventID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, id.RoomID, string) error); ok {
		r1 = rf(ctx, roomID, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBroadcaster_StartJobSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobSession'
type MockBroadcaster_StartJobSession_Call struct {
	*mock.Call
}

// StartJobSession is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID id.RoomID
//   - message string
func (_e *MockBroadcaster_Expecter) StartJobSession(ctx interface{}, roomID interface{}, message interface{}) *MockBroadcaster_StartJobSession_Call {
	return &MockBroadcaster_StartJobSession_Call{Call: _e.mock.On("StartJobSession", ctx, roomID, message)}
}

func (_c *MockBroadcaster_StartJobSession_Call) Run(run func(ctx context.Context, roomID id.RoomID, message string)) *MockBroadcaster_StartJobSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.RoomID), args[2].(string))
	})
	return _c
}

func (_c *MockBroadcaster_StartJobSession_Call) Return(_a0 id.EventID, _a1 error) *MockBroadcaster_StartJobSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBroadcaster_StartJobSession_Call) RunAndReturn(run func(context.Context, id.RoomID, string) (id.EventID, error)) *MockBroadcaster_StartJobSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroadcaster creates a new instance of MockBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcaster {
	mock := &MockBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
