// Code generated by mockery v2.53.6. DO NOT EDIT.

package scheduler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConditionFunc is an autogenerated mock type for the ConditionFunc type
type MockConditionFunc struct {
	mock.Mock
}

type MockConditionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConditionFunc) EXPECT() *MockConditionFunc_Expecter {
	return &MockConditionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockConditionFunc) Execute(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConditionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConditionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConditionFunc_Expecter) Execute(ctx interface{}) *MockConditionFunc_Execute_Call {
	return &MockConditionFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockConditionFunc_Execute_Call) Run(run func(ctx context.Context)) *MockConditionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConditionFunc_Execute_Call) Return(_a0 bool, _a1 error) *MockConditionFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConditionFunc_Execute_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockConditionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConditionFunc creates a new instance of MockConditionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConditionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConditionFunc {
	mock := &MockConditionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
