http:
  routers:
    fedeizzodev:
      entryPoints:
        - "websecure"
      rule: "Host(`fedeizzo.dev`)"
      service: "fedeizzodev"
    fireflyiii:
      entryPoints:
        - "websecure"
      rule: "Host(`firefly.fedeizzo.dev`)"
      service: "fireflyiii"
    grafana:
      entryPoints:
        - "websecure"
      rule: "Host(`grafana.fedeizzo.dev`)"
      service: "grafana"
    nocodb:
      entryPoints:
        - "websecure"
      rule: "Host(`nocodb.fedeizzo.dev`)"
      service: "nocodb"

  services:
    fedeizzodev:
      loadBalancer:
        servers:
          - url: "http://fedeizzodev:80"
    fireflyiii:
      loadBalancer:
        servers:
          - url: "http://fireflyiii:8080"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    nocodb:
      loadBalancer:
        servers:
          - url: "http://nocodb:8080"
