http:
  routers:
    fedeizzodev:
      entryPoints:
        - "websecure"
      rule: "Host(`fedeizzo.dev`)"
      service: "fedeizzodev"
    fireflyiii:
      entryPoints:
        - "websecure"
      rule: "Host(`firefly.fedeizzo.dev`)"
      service: "fireflyiii"

  services:
    fedeizzodev:
      loadBalancer:
        servers:
          - url: "http://fedeizzodev:80"
    fireflyiii:
      loadBalancer:
        servers:
          - url: "http://fireflyiii:8080"
