apiVersion: v1
data:
    CF_API_EMAIL: ENC[AES256_GCM,data:qEFl1CCsgJmp/4mlAK8l2NvE1Lyl57Cxklf71gC9mzx+qZgq,iv:+UqKKlrh00OFWtar8ArO7/XJQWp2JvpHNBNspiO2dGE=,tag:Y+iqMoSHDWuzi7AoF4bF1Q==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:nahyjB9rfojy1Lm1m/51GDjEt4KpjQOP96x9WTxBCSdFi7cM02J6PX/84ahO2UK0bQ7RxQ==,iv:Qi1OZKYfpRx+lAR1/aYFnrgQ/hlrquS6IY9ti9Dp2hQ=,tag:S/InkKxV4Z99jTd/eJYoaQ==,type:str]
kind: Secret
type: Opaque
metadata:
    creationTimestamp: null
    name: traefik-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162fef9eha0za3r97qk7jaw7y87wlj5lgzl8laqemagqsftq7693sckrcc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOTVYbkk4NVRmTCs3R0ZW
            ekNXNXN2UWcvOTVYbVVreS81M3pncHdBUXpVCmVqVHcvVml2TCtXK01LTWhTUUdO
            blhjYy82bnRBK0M2SXF0eFBQOERKbHcKLS0tIFhYNFJBZk03bjBOamo2RkdZbFl2
            RkZ1T3FuaEd1MnBWQXF3KzAvc1dBN2cK7Dim6LHhxbCL03PUBURetTOdFapZd+Qm
            OR4hQmX5wyvlUKijcocrBjGXMJUVvIfFoXzkpduYWI1EqVWtO9Hl3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14jd2uvg5fwc2r2vgp4tsw5dy9rpksel97um2v494ws4tptult9ys50cndr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDJ5VUxNTEVaYW04ejFF
            T05JQUEySm9DOENzeXovSXRIdVpwZnZ2ZzJFCldZZUw1ZjM1WEkwczdMVVkxQmZG
            dERzOU5CRkRiWU04RVFhS3V0VG1kKzAKLS0tIENKZzhwTmRTZEJJTGhXbmdLektV
            eHhsVDBySTY3NUQweXBBZUc4dFZxWjAKxftASnP2tmZFF+8e95KDndkNkWFds9+8
            T+POGuSGvrdBusbyd5ybBF7UK5jSQTx/OUgE05EPQSTDxVr7sMHjZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T15:09:17Z"
    mac: ENC[AES256_GCM,data:SLb1VXFy3gNbR+SI88iZmIInoYMuqZWLTWUaJvh4jiKCyOmTwkoQT7W9TPqyizTK/CM0M4Ufo2KTGMaoltOarmzqtHQ786Ls7PoaUeovLQWUvtVDEE4hXM9rBaBBUMIuRwRJARadUEdRbZIhpVs+6ViKxSttrD0lPIf5Ry02D68=,iv:Hkew3mUlVwnVEYgueuy19cMdeYFmk4f8fFQVhyuhLF8=,tag:f3YKZr0CseUKkb2jM1KnuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
