kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.8
          args:
            - --api.insecure # disable this in production
            - --providers.kubernetesingress
            # HTTPS
            # - --entrypoints.web.http.redirections.entryPoint.to=websecure
            # - --entryPoints.websecure.address=:443
            # - --entrypoints.websecure.http.tls
            # CERTIFICATES
            # - --certificatesresolvers.myresolver.acme.email=federico.izzo99@gmail.com # indirizzo a caso su mio dominio
            # - --certificatesresolvers.myresolver.acme.storage=/acme.json
            # - --certificatesresolvers.myresolver.acme.dnschallenge=true
            # - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
            # - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
