#pragma once
#define MASTER_RIGHT

#define TAPPING_TERM 175
#define AUTO_SHIFT_TIMEOUT 175
#define AUTO_SHIFT_REPEAT
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC

#define IGNORE_MOD_TAP_INTERRUPT
