AUDIO_ENABLE = no          # Audio output
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
BOOTMAGIC_ENABLE = no      # Enable Bootmagic Lite
COMMAND_ENABLE = no        # Commands for debug and configuration
AUTO_SHIFT_ENABLE = no
BLUETOOTH_ENABLE = no
CONSOLE_ENABLE = no        # Console for debug
EXTRAKEY_ENABLE =  yes     # Audio control and System control
MOUSEKEY_ENABLE = no       # Mouse keys
NKRO_ENABLE = no
OLED_ENABLE= no            # OLED display
RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
SPACE_CADET_ENABLE=no
SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = no     # Enable one-hand typing
TAP_DANCE_ENABLE = no
