-- PLUGINS DOWNLOAD
require('plugins')

-- NEOVIM CORE OPTIONS
require('nvim-core')

-- CUSTOM FUNCTION
require('scripts/automatic-output')
require('scripts/enumerate-python-for')
require('scripts/telescope-file')
require('scripts/notes-manager')

-- PLUGINS SETTINGS
require('plugins/accelerated')
require('plugins/comment')
require('plugins/dashboard')
require('plugins/diagnostic')
require('plugins/formatter')
require('plugins/gitsigns')
require('plugins/haskell-vim')
require('plugins/indentblankline')
require('plugins/init')
require('plugins/iron')
require('plugins/lightspeed')
require('plugins/lualine')
require('plugins/mkdx')
require('plugins/nvim-autopairs')
require('plugins/nvim-cmp')
require('plugins/nvim-dap')
require('plugins/telescope')
require('plugins/toggleterm')
require('plugins/treesitter')
require('plugins/twilight')
require('plugins/vim-json')
require('plugins/vimmarkdown')
require('plugins/vsnip')
require('plugins/which-key')

-- LANGUAGES SETTINGS
require('languages/bash')
require('languages/c')
require('languages/docker')
require('languages/haskell')
require('languages/lua')
require('languages/md')
require('languages/nix')
require('languages/python')
require('languages/rust')
require('languages/typescript')
require('languages/vim')
