#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

Sound(){
    local SINK=$(pactl list short sinks | grep RUNNING | cut -f1)
    local VOL=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
    local muted=$( pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' | cut -d: -f2)

    local config=$(readConfig "sound")
    local color=$white
    local icon

	if [[ $muted == " no" ]] ; then
		if [ $VOL -ge 50 ] ; then
            icon=""
		else
            icon=""
		fi
	else
        icon=""
	fi
    if [[ $config == 'reduced' ]]
    then
        echo -e "%{A6:sound expanded:}%{A7:sound reduced:} %{F$color}$icon%{F$white} %{A}%{A}"
    else
        echo -e "%{A6:sound expanded:}%{A7:sound reduced:} %{F$color}$icon%{F$white} $volume%{A}%{A}"
    fi
}

Sound
