#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

Temp() {
    local temp=$(sensors | awk -F: '/temp1/{print $2}' | sed '1d' | sed -E 's/ //g')
    local number=$(echo $temp | awk -F. '{print $1}' | sed 's/+//g')
    local config=$(readConfig "temp")
    local color
    local icon
    if [[ $number -le 45 ]]
    then
        color=$green
        icon=''
    elif [[ $number -ge 75 ]]
    then
        color=$red
        icon=''
    else
        color=$yellow
        icon=''
    fi

    if [[ $config == 'reduced' ]]
    then
        echo -e "%{A6:temp expanded:}%{A7:temp reduced:} %{F$color}$icon%{F$white} %{A}%{A}"
    else
        echo -e "%{A6:temp expanded:}%{A7:temp reduced:} %{F$color}$icon%{F$white} $temp %{A}%{A}"
    fi
}

Temp
