#!/usr/bin/env bash

###################################################################
#Script Name	: backup
#Description	: routine for bakup with borg
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 21/09/2020
###################################################################

info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"
sudo borg create \
    --progress \
    --stats \
    --show-rc \
    --exclude-caches \
    --exclude '/home/*/.cache/*' \
    --exclude '/home/*/cache/*' \
    --exclude '/home/*/Cache/*' \
    --exclude '/home/fedeizzo/.local/share/Steam/*' \
    --exclude '/home/fedeizzo/.local/share/lutris/*' \
    --exclude '/home/fedeizzo/.wine/*' \
    --exclude '/home/*/.npm/_cacache/*' \
    --exclude '/var/cache/*' \
    --exclude '/var/*/.cache/*' \
    --exclude '/var/tmp/*' \
    --exclude '/data/borgBackups/*' \
    --exclude '/data/*/node_modules/*' \
    --exclude '/data/SteamLibrary/*'   \
    --exclude '/data/Games/*'   \
    /data/borgBackups::'{hostname}-{now}' /home /var /etc /data
backup_exit=$?

sudo borg prune \
    --progress \
    --prefix '{hostname}-' \
    --show-rc \
    --keep-daily 1 \
    --keep-weekly 3 \
    --keep-monthly 4 \
    /data/borgBackups
prune_exit=$?

global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))


if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}
