#!/usr/bin/env bash

###################################################################
#Script Name	: autorenameNodes
#Description	: rename desktop with awesome icons
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 21/09/2020
###################################################################

declare -A mapper
mapper[Alacritty]=""
mapper[fzf]=""
mapper[firefox]=""
mapper[llpp]=""
mapper[gimp]=""
mapper[libreoffice]=""
mapper[VSCodium]=""
mapper[vlc]=""
mapper[TelegramDesktop]=""
mapper[TeamViewer]=""
mapper[Zathura]=""
mapper[Pavucontrol]=""
mapper[qutebrowser]=""

renameDesktop() {
    local desktop
    desktop="$1"
    currentName=$(bspc query -D -d $desktop --names | tr -dc '0-9')
    bspc desktop $desktop -n $currentName
    while read line
    do
        if [ ${mapper[$line]+_} ]; then icon=${mapper[$line]}; else icon="?"; fi
        bspc desktop $desktop -n "$currentName $icon"
        currentName=$currentName" "$icon
        # echo $currentName
        echo $line
    done < <(bspc query -d $desktop -T | jshon | grep className | cut -d '"' -f4)
}

bspc subscribe node_add node_remove node_transfer | while read -a msg
do
    monitor=${msg[1]}
    desktop=${msg[2]}
    if [[ ${msg[0]} == "node_add" ]]
    then
        node=${msg[4]}
    elif [[ ${msg[0]} == "node_remove" ]]
    then
        node=${msg[3]}
    elif [[ ${msg[0]} == "node_transfer" ]]
    then
        dst=${msg[5]}
        renameDesktop $desktop
        renameDesktop $dst
        # echo "from"
        # bspc query -d $desktop -T | jshon | grep className | cut -d '"' -f4
        # echo "to"
        # bspc query -d $dst -T | jshon | grep className | cut -d '"' -f4
    fi
    renameDesktop $desktop
done
