#!/usr/bin/env bash

###################################################################
#Script Name	: cpuUsage
#Description	: output cpu usage in percentage
#Args         	: core to inspect
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24-02-2020
###################################################################

helpMessage="usage: cpuUsage <core>"

[ -z $1 ] && echo -e $helpMessage && exit

echo $(cat <(grep "cpu$1" /proc/stat) <(sleep 0.05 && grep "cpu$1" /proc/stat) | awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}')
