#!/usr/bin/env bash

###################################################################
#Script Name	: saveImage
#Description	: save image from the clipboard
#Args         	: name of the image
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

helpMessage="usage: saveImage <name of image>"

[ -z $1 ] && echo -e $helpMessage && exit

position=$(pwd)
path=$position'/'$1'.png'
xclip -selection clipboard -t image/png -o p.png > $path
