#!/usr/bin/env bash

###################################################################
#Script Name	: threeFourScreen
#Description	: add 3/4 of the width on focused node
#Args         	: direction
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

helpMessage="error"

[ -z $1 ] && echo -e $helpMessage && exit

dir=$1
coords=$(xwininfo -id $(xdotool getactivewindow) | sed '4,9!d' | sed '3,4d' | gawk -F: '{print $2}')

set $coords
x=$1
y=$2
width=$3
height=$4
if [[ $dir == "expand" ]]
then
    if [[ $x == 7 ]]
    then
        bspc node -z right $((( $width / 2))) 0
    else
        bspc node -z left -$((( $width / 2))) 0
    fi
elif [[ $dir == "reduce" ]]
then
    if [[ $x == 7 ]]
    then
        bspc node -z right -$((( $width / 3))) 0
    else
        bspc node -z left $((( $width / 3))) 0
    fi
fi
