#!/usr/bin/env bash

###################################################################
#Script Name	: launcheConky
#Description	: kill all istances of conky and run it
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

# Terminate already running bar instances
killall -q conky

# Wait until the processes have been shut down
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done

# Launch bar1 and bar2
conky -b -d &
