#!/usr/bin/env bash

SINK=$(pactl list short sinks | grep RUNNING | cut -f1)
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
if [[ $1 == "+" ]]
then
    if [[ $NOW != "100" ]]
    then
        pactl set-sink-volume $SINK "+1%"
    fi
elif [[ $1 == "-" ]]
then
        pactl set-sink-volume $SINK "-1%"
fi
