#!/usr/bin/env bash

###################################################################
#Script Name	: launcheSpotifyd
#Description	: kill all instances of spotifyd and run it
#Args         	: none
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 12/04/2020
###################################################################

# Terminate already running spotifyd instances
killall -q spotifyd

# Wait until the processes have been shut down
while pgrep -u $UID -x spotifyd >/dev/null; do sleep 1; done
# while ps -A | grep polybar >/dev/null; do sleep 1; done

# Launch spotifyd
spotifyd
