#!/usr/bin/env bash

###################################################################
#Script Name	: shiftCommand
#Description	: run program with empty desktop
#Args         	: option
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 29/01/2020
###################################################################

helpMessage="usage: shiftCommand <option>"

[ -z $1 ] && echo -e $helpMessage && exit

option=$1

bspc query -D -d focused -n &> /dev/null
if [[ $? == 1 ]]
then
    case "$option" in
        --work|-w)
            workStartup
            ;;
        --vim|-v)
            $TERMINAL -e nvim
    esac
fi
