#!/usr/bin/env bash

[ -z $1 ] && echo "usage: bluetooth <device>" && exit

KEYBOARD="F8:30:02:49:A1:76"
HEADSET="38:18:4C:D4:10:3C"
SPEAKER="C0:28:8D:85:B6:47"

Print() {
    if [[ "$(bluetoothctl info $1 | grep "Connected: yes")" = *Connected:\ yes ]]; then
        echo "connected"
    else
        echo "disconnected"
    fi
}

if [[ $1 == "print" ]]
then
    shift
    if [[ $1 == "keyboard" ]]
    then
        Print $KEYBOARD
    elif [[ $1 == "headset" ]]
    then
        Print $HEADSET
    elif [[ $1 == "speaker" ]]
    then
        Print $SPEAKER
    fi
elif [[ $1 == "toggle" ]]
then
    shift
    if [[ $1 == "keyboard" ]]
    then
        Toggle $KEYBOARD
    elif [[ $1 == "headset" ]]
    then
        Toggle $HEADSET
    elif [[ $1 == "speaker" ]]
    then
        Toggle $SPEAKER
    fi
else
    echo -e "bad usage"
    exit 1
fi
