#!/usr/bin/env bash

###################################################################
#Script Name	: img
#Description	: display image in a terminal
#Args         	: image and coords of image
#Author       	: Federico Izzo
#Email         	: federico.izzo99@gmail.com
#Last Update    : 24/01/2020
###################################################################

helpMessage="Usage: $0 <image> <x> <y> <max height> <max width>"

[ -z "$5" ] && echo -e $helpMessage && exit
source "`ueberzug library`"

ImageLayer 0< <(
    ImageLayer::add [identifier]="example0" [x]="$2" [y]="$3" [max_width]="$5" [max_height]="$4" [path]="$1"
    read
)
