#!/usr/bin/env bash

chosen=$(echo -e "Laptop\nHDMI\nHDMI up\nDP1 up" | rofi -dmenu -i -p " ")

if [[ $chosen = "Laptop" ]]; then
    changeMonitor eDP1
elif [[ $chosen = "HDMI" ]]; then
    changeMonitor hdmi
elif [[ $chosen = "HDMI up" ]]; then
    changeMonitor hdmiUp
elif [[ $chosen = "DP1 up" ]]; then
    changeMonitor DP1Up
fi
