#!/usr/bin/env bash

# Terminate already running bar instances
killall -q lemonbar

# Wait until the processes have been shut down
while pgrep -u $UID -x lemonbar >/dev/null; do sleep 1; done

monitorPlugged=$(xrandr -q | grep '^DP1' | awk '{print $2}')
if [[ $monitorPlugged == "connected" ]]
then
    width=1680
else
    width=1920
fi

lemonblocks $1 | lemonbar -g $width"x17" -p -H -B '#00000000' -o -1 -f 'RobotoMono Nerd Font Mono:size=10' | while read line
do
    read -ra output <<< "$line"
    if [[ ${output[0]} == "headset" ]]
    then
        headset
    elif [[ ${output[0]} == "cal" ]]
    then
        notify-send "$(cal)"
    else
        if [[ ${output[1]} == "expanded" ]]
        then
            sed -i "s/${output[0]}.reduced/${output[0]}.expanded/g" $XDG_CONFIG_HOME/lemonbar/config
        else
            sed -i "s/${output[0]}.expanded/${output[0]}.reduced/g" $XDG_CONFIG_HOME/lemonbar/config
        fi
    fi
done & disown
