#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

DrawWorkspace() {
    local occ=$(bspc query -m $1 -D -d .occupied --names | cut -d' ' -f1 | sed ':a;n;$!ba;s/\n/ /g')
    local num_foc=$(bspc query -m $1 -D -d .active --names | cut -d' ' -f1)

    local circle_full=""
    local output
    local desktop
    desktop=(%{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus} %{F$whiteUnfocus}%{F$white})
    occ=($occ)
    for i in "${occ[@]}"
    do
        desktop[$i - 1]="%{F$white}%{F$white}"
    done
    desktop[$num_foc - 1 ]="%{F$green}%{F$white}"
    echo -e ${desktop[@]}
}

printBspwm(){
    local monitorHdmi=$(xrandr -q | grep HDMI1 | awk '{print $2}')
    local isHdmiPrimary=$(xrandr -q | grep HDMI1 | awk '{print $3}')
    local monitorDp1=$(xrandr -q | grep '^DP1' | awk '{print $2}')

    if [[ $isHdmiPrimary == "primary" ]]
    then
        DrawWorkspace "HDMI1"
    elif [[ $monitorHdmi == "connected" ]]
    then
        local edp1=$(DrawWorkspace "eDP1")
        local hdmi=$(DrawWorkspace "HDMI1")
        echo -e $edp1" | "$hdmi
    elif [[ $monitorDp1 == "connected" ]]
    then
        local dp1=$(DrawWorkspace "DP1")
        local hdmi=$(DrawWorkspace "HDMI1")
        echo -e $edp1" | "$hdmi
    else
        DrawWorkspace "eDP1"
    fi
}

printBspwm
