#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

Cpu() {
    local config=$(readConfig "cpu")
    local color=$white
    local icon=""

    if [[ $config == 'reduced' ]]
    then
        echo -e "%{A6:cpu expanded:}%{A7:cpu reduced:} %{F$color}$icon%{F$white} %{A}%{A}"
    else
        local core0=$(cpuUsage 0)
        local core1=$(cpuUsage 1)
        local core2=$(cpuUsage 2)
        local core3=$(cpuUsage 3)
        echo -e "%{A6:cpu expanded:}%{A7:cpu reduced:} %{F$color}$icon%{F$white} $core0% $core1% $core2% $core3%  %{A}%{A}"
    fi
}

Cpu
