#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

Backlight() {
    local config=$(readConfig "light")
    local color=$white
    local icon=""

    if [[ $config == 'reduced' ]]
    then
        echo -e "%{A6:light expanded:}%{A7:light reduced:} %{F$color}$icon%{F$white} %{A}%{A}"
    else
        local light=$(light)
        echo -e "%{A6:light expanded:}%{A7:light reduced:} %{F$color}$icon%{F$white} $light %{A}%{A}"
    fi
}
Backlight
