#!/usr/bin/env bash

white="#FFFFFF"
whiteUnfocus="#55FFFFFF"
red='#FF0000'
green='#1db954'
yellow='#FFFF00'

Memory() {
    local mem=$(free -h --si | awk -F' ' '/Mem/{print $3}')
    local number=$(echo $mem | sed 's/M\|G//g')
    local config=$(readConfig "mem")
    local color
    local icon=""
    # TODO fix
    # case with mega
    if (( $(echo "$number > 100" | bc -l)))
    then
        color=$green
    elif (( $(echo "$number < 4" | bc -l) ))
    then
        color=$green
    elif (( $(echo "$number > 8" |bc -l) ))
    then
        color=$red
    else
        color=$yellow
    fi

    if [[ $config == 'reduced' ]]
    then
        echo -e "%{A6:mem expanded:}%{A7:mem reduced:} %{F$color}$icon%{F$white} %{A}%{A}"
    else
        echo -e "%{A6:mem expanded:}%{A7:mem reduced:} %{F$color}$icon%{F$white} $mem %{A}%{A}"
    fi
}

Memory
