apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedeizzodev
  labels:
    app: fedeizzodev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedeizzodev
  template:
    metadata:
      labels:
        app: fedeizzodev
    spec:
      containers:
      - name: fedeizzodev
        image: fedeizzo/website:latest
        imagePullPolicy: Always
        tty: true
        ports:
        - name: website-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fedeizzodev-service
spec:
  selector:
    app: fedeizzodev
  ports:
    - protocol: TCP
      name: website-port
      port: 80
      targetPort: website-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedeizzodev-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure" # to use https globally
    traefik.ingress.kubernetes.io/router.tls: "true" # to use htpss when tls is not set globally
    traefik.ingress.kubernetes.io/router.tls.resolver: "le" # to use htpss when tls is not set globally
  # traefik.ingress.kubernetes.io/service.serversscheme: https # to use https in the comunication between traefik and the service
spec:
  rules:
  - host: "fedeizzo.dev"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: fedeizzodev-service
            port:
              name: website-port
