#!/usr/bin/env bash


case $1 in
    trackpad)
        upower -i /org/freedesktop/UPower/devices/battery_hid_30o82o16of2o86oc6_battery | grep percentage | awk -F':' '{print $2}' | tr -d ' ' | tr -d '%'
        if [[ val =~ ".*shouldbeingored" ]]; then
            exit 0
        fi
        ;;
    headset)
        val=$(upower -i /org/freedesktop/UPower/devices/headphones_dev_C8_7B_23_A4_3B_2A | grep percentage | awk -F':' '{print $2}' | tr -d ' ' | tr -d '%')
        if [[ val =~ ".*shouldbeingored" ]]; then
            exit 0
        fi
        ;;
    chocofi_left)
        ~/nix-dotfiles/home/xps-9510/modules/wayland/eww/scripts/zmk_batt FD:0E:63:E8:08:E1 | awk -F',' '{print $1}' | tr -d '['
        ;;
    chocofi_right)
        ~/nix-dotfiles/home/xps-9510/modules/wayland/eww/scripts/zmk_batt FD:0E:63:E8:08:E1| awk -F',' '{print $2}' | tr -d ']'
        ;;
esac
