apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      volumes:
      - name: cloudflare-ddns-config
        hostPath:
          path: /var/volumes/cloudflare-ddns/config.json
      containers:
      - name: cloudflare-ddns
        image: timothyjmiller/cloudflare-ddns:latest
        volumeMounts:
        - name: cloudflare-ddns-config
          mountPath: /config.json
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: PGID
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cloudflare-ddns-service
# spec:
#   selector:
#     app: cloudflare-ddns
