# apiVersion: apiextensions.k8s.io/v1beta1
# kind: CustomResourceDefinition
# metadata:
#   name: middlewaretcps.traefik.containo.us
# spec:
#   group: traefik.containo.us
#   version: v1alpha1
#   names:
#     kind: MiddlewareTCP
#     plural: middlewaretcps
#     singular: middlewaretcp
#   scope: Namespaced
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: MiddlewareTCP
# metadata:
#   name: wireguard-ipwhitelist
# spec:
#   ipWhiteList:
#     sourceRange:
#        - 192.168.100.2/24
