// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"pan/internal/tool/lunchmoney"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/adk/tool"
)

// NewMockLunchMoneyToolset creates a new instance of MockLunchMoneyToolset. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLunchMoneyToolset(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLunchMoneyToolset {
	mock := &MockLunchMoneyToolset{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLunchMoneyToolset is an autogenerated mock type for the LunchMoneyToolset type
type MockLunchMoneyToolset struct {
	mock.Mock
}

type MockLunchMoneyToolset_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLunchMoneyToolset) EXPECT() *MockLunchMoneyToolset_Expecter {
	return &MockLunchMoneyToolset_Expecter{mock: &_m.Mock}
}

// GetCategories provides a mock function for the type MockLunchMoneyToolset
func (_mock *MockLunchMoneyToolset) GetCategories(ctx tool.Context, input lunchmoney.GetCategoriesInput) (lunchmoney.GetCategoriesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 lunchmoney.GetCategoriesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetCategoriesInput) (lunchmoney.GetCategoriesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetCategoriesInput) lunchmoney.GetCategoriesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(lunchmoney.GetCategoriesOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(tool.Context, lunchmoney.GetCategoriesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLunchMoneyToolset_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type MockLunchMoneyToolset_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx tool.Context
//   - input lunchmoney.GetCategoriesInput
func (_e *MockLunchMoneyToolset_Expecter) GetCategories(ctx interface{}, input interface{}) *MockLunchMoneyToolset_GetCategories_Call {
	return &MockLunchMoneyToolset_GetCategories_Call{Call: _e.mock.On("GetCategories", ctx, input)}
}

func (_c *MockLunchMoneyToolset_GetCategories_Call) Run(run func(ctx tool.Context, input lunchmoney.GetCategoriesInput)) *MockLunchMoneyToolset_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tool.Context
		if args[0] != nil {
			arg0 = args[0].(tool.Context)
		}
		var arg1 lunchmoney.GetCategoriesInput
		if args[1] != nil {
			arg1 = args[1].(lunchmoney.GetCategoriesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLunchMoneyToolset_GetCategories_Call) Return(getCategoriesOutput lunchmoney.GetCategoriesOutput, err error) *MockLunchMoneyToolset_GetCategories_Call {
	_c.Call.Return(getCategoriesOutput, err)
	return _c
}

func (_c *MockLunchMoneyToolset_GetCategories_Call) RunAndReturn(run func(ctx tool.Context, input lunchmoney.GetCategoriesInput) (lunchmoney.GetCategoriesOutput, error)) *MockLunchMoneyToolset_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestUnreviewedTransaction provides a mock function for the type MockLunchMoneyToolset
func (_mock *MockLunchMoneyToolset) GetLatestUnreviewedTransaction(ctx tool.Context, input lunchmoney.GetLatestUnreviewedTransactionInput) (lunchmoney.GetLatestUnreviewedTransactionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestUnreviewedTransaction")
	}

	var r0 lunchmoney.GetLatestUnreviewedTransactionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetLatestUnreviewedTransactionInput) (lunchmoney.GetLatestUnreviewedTransactionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetLatestUnreviewedTransactionInput) lunchmoney.GetLatestUnreviewedTransactionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(lunchmoney.GetLatestUnreviewedTransactionOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(tool.Context, lunchmoney.GetLatestUnreviewedTransactionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestUnreviewedTransaction'
type MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call struct {
	*mock.Call
}

// GetLatestUnreviewedTransaction is a helper method to define mock.On call
//   - ctx tool.Context
//   - input lunchmoney.GetLatestUnreviewedTransactionInput
func (_e *MockLunchMoneyToolset_Expecter) GetLatestUnreviewedTransaction(ctx interface{}, input interface{}) *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call {
	return &MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call{Call: _e.mock.On("GetLatestUnreviewedTransaction", ctx, input)}
}

func (_c *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call) Run(run func(ctx tool.Context, input lunchmoney.GetLatestUnreviewedTransactionInput)) *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tool.Context
		if args[0] != nil {
			arg0 = args[0].(tool.Context)
		}
		var arg1 lunchmoney.GetLatestUnreviewedTransactionInput
		if args[1] != nil {
			arg1 = args[1].(lunchmoney.GetLatestUnreviewedTransactionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call) Return(getLatestUnreviewedTransactionOutput lunchmoney.GetLatestUnreviewedTransactionOutput, err error) *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call {
	_c.Call.Return(getLatestUnreviewedTransactionOutput, err)
	return _c
}

func (_c *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call) RunAndReturn(run func(ctx tool.Context, input lunchmoney.GetLatestUnreviewedTransactionInput) (lunchmoney.GetLatestUnreviewedTransactionOutput, error)) *MockLunchMoneyToolset_GetLatestUnreviewedTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function for the type MockLunchMoneyToolset
func (_mock *MockLunchMoneyToolset) GetTags(ctx tool.Context, input lunchmoney.GetTagsInput) (lunchmoney.GetTagsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 lunchmoney.GetTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetTagsInput) (lunchmoney.GetTagsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.GetTagsInput) lunchmoney.GetTagsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(lunchmoney.GetTagsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(tool.Context, lunchmoney.GetTagsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLunchMoneyToolset_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockLunchMoneyToolset_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - ctx tool.Context
//   - input lunchmoney.GetTagsInput
func (_e *MockLunchMoneyToolset_Expecter) GetTags(ctx interface{}, input interface{}) *MockLunchMoneyToolset_GetTags_Call {
	return &MockLunchMoneyToolset_GetTags_Call{Call: _e.mock.On("GetTags", ctx, input)}
}

func (_c *MockLunchMoneyToolset_GetTags_Call) Run(run func(ctx tool.Context, input lunchmoney.GetTagsInput)) *MockLunchMoneyToolset_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tool.Context
		if args[0] != nil {
			arg0 = args[0].(tool.Context)
		}
		var arg1 lunchmoney.GetTagsInput
		if args[1] != nil {
			arg1 = args[1].(lunchmoney.GetTagsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLunchMoneyToolset_GetTags_Call) Return(getTagsOutput lunchmoney.GetTagsOutput, err error) *MockLunchMoneyToolset_GetTags_Call {
	_c.Call.Return(getTagsOutput, err)
	return _c
}

func (_c *MockLunchMoneyToolset_GetTags_Call) RunAndReturn(run func(ctx tool.Context, input lunchmoney.GetTagsInput) (lunchmoney.GetTagsOutput, error)) *MockLunchMoneyToolset_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function for the type MockLunchMoneyToolset
func (_mock *MockLunchMoneyToolset) UpdateTransaction(ctx tool.Context, input lunchmoney.UpdateTransactionInput) (lunchmoney.UpdateTransactionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 lunchmoney.UpdateTransactionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.UpdateTransactionInput) (lunchmoney.UpdateTransactionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(tool.Context, lunchmoney.UpdateTransactionInput) lunchmoney.UpdateTransactionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(lunchmoney.UpdateTransactionOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(tool.Context, lunchmoney.UpdateTransactionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLunchMoneyToolset_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type MockLunchMoneyToolset_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx tool.Context
//   - input lunchmoney.UpdateTransactionInput
func (_e *MockLunchMoneyToolset_Expecter) UpdateTransaction(ctx interface{}, input interface{}) *MockLunchMoneyToolset_UpdateTransaction_Call {
	return &MockLunchMoneyToolset_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, input)}
}

func (_c *MockLunchMoneyToolset_UpdateTransaction_Call) Run(run func(ctx tool.Context, input lunchmoney.UpdateTransactionInput)) *MockLunchMoneyToolset_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tool.Context
		if args[0] != nil {
			arg0 = args[0].(tool.Context)
		}
		var arg1 lunchmoney.UpdateTransactionInput
		if args[1] != nil {
			arg1 = args[1].(lunchmoney.UpdateTransactionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLunchMoneyToolset_UpdateTransaction_Call) Return(updateTransactionOutput lunchmoney.UpdateTransactionOutput, err error) *MockLunchMoneyToolset_UpdateTransaction_Call {
	_c.Call.Return(updateTransactionOutput, err)
	return _c
}

func (_c *MockLunchMoneyToolset_UpdateTransaction_Call) RunAndReturn(run func(ctx tool.Context, input lunchmoney.UpdateTransactionInput) (lunchmoney.UpdateTransactionOutput, error)) *MockLunchMoneyToolset_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}
