default:
    @just --list

# Format the code to standard Rust idioms
fmt:
    cargo fmt

# Run the aggressive clippy linter
lint:
    cargo clippy -- -W clippy::pedantic

# Run all tests using standard cargo test
test:
    cargo test

# Run all tests using nextest for beautiful output
nextest:
    cargo nextest run --status-level pass

# Continuously watch for changes and run nextest
watch:
    cargo watch -x "nextest run"

# Run test coverage with cargo-tarpaulin
coverage:
    cargo tarpaulin

# Build the binary
build:
    cargo build

# Run the application (e.g. `just run --config config.yml`)
run *ARGS:
    cargo run -- {{ARGS}}

# Run format, lint, and test (Run this before you commit!)
check: fmt lint nextest
