no match command: qutebrowser
iterate over PATH: true
directory: 
    name: PDF vari
    path: /data/libriVari/
    pattern: *.pdf
    recursive: true
    program: zathura
    icon: 
directory: 
    name: PDF uni
    path: /data/secondoAnno/
    pattern: *.pdf
    recursive: true
    program: zathura
    icon: 
