// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fusion

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFusionService creates a new instance of MockFusionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFusionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFusionService {
	mock := &MockFusionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFusionService is an autogenerated mock type for the FusionService type
type MockFusionService struct {
	mock.Mock
}

type MockFusionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFusionService) EXPECT() *MockFusionService_Expecter {
	return &MockFusionService_Expecter{mock: &_m.Mock}
}

// GetUnreadFeeds provides a mock function for the type MockFusionService
func (_mock *MockFusionService) GetUnreadFeeds(ctx context.Context, limit int) ([]FeedItem, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadFeeds")
	}

	var r0 []FeedItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]FeedItem, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []FeedItem); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FeedItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFusionService_GetUnreadFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadFeeds'
type MockFusionService_GetUnreadFeeds_Call struct {
	*mock.Call
}

// GetUnreadFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockFusionService_Expecter) GetUnreadFeeds(ctx interface{}, limit interface{}) *MockFusionService_GetUnreadFeeds_Call {
	return &MockFusionService_GetUnreadFeeds_Call{Call: _e.mock.On("GetUnreadFeeds", ctx, limit)}
}

func (_c *MockFusionService_GetUnreadFeeds_Call) Run(run func(ctx context.Context, limit int)) *MockFusionService_GetUnreadFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFusionService_GetUnreadFeeds_Call) Return(feedItems []FeedItem, err error) *MockFusionService_GetUnreadFeeds_Call {
	_c.Call.Return(feedItems, err)
	return _c
}

func (_c *MockFusionService_GetUnreadFeeds_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]FeedItem, error)) *MockFusionService_GetUnreadFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFeedsAsRead provides a mock function for the type MockFusionService
func (_mock *MockFusionService) MarkFeedsAsRead(ctx context.Context, ids []int) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkFeedsAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFusionService_MarkFeedsAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFeedsAsRead'
type MockFusionService_MarkFeedsAsRead_Call struct {
	*mock.Call
}

// MarkFeedsAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockFusionService_Expecter) MarkFeedsAsRead(ctx interface{}, ids interface{}) *MockFusionService_MarkFeedsAsRead_Call {
	return &MockFusionService_MarkFeedsAsRead_Call{Call: _e.mock.On("MarkFeedsAsRead", ctx, ids)}
}

func (_c *MockFusionService_MarkFeedsAsRead_Call) Run(run func(ctx context.Context, ids []int)) *MockFusionService_MarkFeedsAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFusionService_MarkFeedsAsRead_Call) Return(err error) *MockFusionService_MarkFeedsAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFusionService_MarkFeedsAsRead_Call) RunAndReturn(run func(ctx context.Context, ids []int) error) *MockFusionService_MarkFeedsAsRead_Call {
	_c.Call.Return(run)
	return _c
}
